/* AULA 06 - PROGRAMA 04 - 20/03/2025
        SEMÁFORO DE DUAS RUAS
PROGRAMA QUE FAZ A LÓGICA DE UM SEMÁFORO DE DUAS RUAS.
O LED VERDE DA RUA 1 COMEÇA LIGADO;
FOI USADO UM LED VERDE NO PINO 5, PARA A RUA 1;
FOI USADO UM LED AMARELO NO PINO 4, PARA A RUA 1;
FOI USADO UM LED VERMELHO NO PINO 3, PARA A RUA 1;
FOI USADO UM LED VERDE NO PINO 13, PARA A RUA 2;
FOI USADO UM LED AMARELO NO PINO 12, PARA A RUA 2;
FOI USADO UM LED VERMELHO NO PINO 11, PARA A RUA 2;
OS RESISTORES USADOS SÃO DE 330R.
PROGRAMA CRIADO PELA NATALIA
*/

#define VERDE1 5 //CRIA A VARIÁVEL
#define AMARELO1 4 //CRIA A VARIÁVEL
#define VERMELHO1 3 //CRIA A VARIÁVEL
#define VERDE2 13 //CRIA A VARIÁVEL
#define AMARELO2 12 //CRIA A VARIÁVEL
#define VERMELHO2 11 //CRIA A VARIÁVEL

void setup() //FUNÇÃO EXECUTADA SÓ UMA VEZ
{
  pinMode(VERDE1, OUTPUT); //DEFINE COMO SAÍDA
  pinMode(AMARELO1, OUTPUT); //DEFINE COMO SAÍDA
  pinMode(VERMELHO1, OUTPUT); //DEFINE COMO SAÍDA
  pinMode(VERDE2, OUTPUT); //DEFINE COMO SAÍDA
  pinMode(AMARELO2, OUTPUT); //DEFINE COMO SAÍDA
  pinMode(VERMELHO2, OUTPUT); //DEFINE COMO SAÍDA
}

void loop() //FUNÇÃO EXECUTADA VARIAS VEZES, PROGRAMAÇÃO
{
  digitalWrite(VERDE1, HIGH); //LIGA O VERDE1
  digitalWrite(VERMELHO2, HIGH); //LIGA O VERMELHO2
  delay(8000); //ESPERA 8 SEGUNDOS
  digitalWrite(VERDE1, LOW); //DESLIGA O VERDE1
  digitalWrite(AMARELO1, HIGH); //LIGA O AMARELO1
  delay(2000); //ESPERA 2 SEGUNDOS
  digitalWrite(AMARELO1, LOW); //DESLIGA O AMARELO1
  digitalWrite(VERMELHO1, HIGH); //LIGA O VERMELHO1
  digitalWrite(VERMELHO2, LOW); //DESLIGA O VERMELHO2
  digitalWrite(VERDE2, HIGH); //LIGA O VERDE2
  delay(8000); //ESPERA 8 SEGUNDOS
  digitalWrite(VERDE2, LOW); //DESLIGA O VERDE2
  digitalWrite(AMARELO2, HIGH); //LIGA O AMARELO2
  delay(2000); //ESPERA 2 SEGUNDOS
  digitalWrite(VERMELHO1, LOW); //DESLIGAO VERMELHO1
  digitalWrite(AMARELO2, LOW); //DESLIGA O AMARELO2
}
